server:
  shutdown: graceful

spring:
  devtools:
    restart:
      # 热部署是否生效
      enabled: false
  # 优雅停机等待时间
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhaoyun?${custom.datasource.url-param}
    username: root
    password: 1pTVg0ld@1909

springfox:
  documentation:
    enabled: false
    swagger-ui:
      enabled: ${springfox.documentation.enabled}
