server:
  port: 8080
  servlet:
    context-path:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: zhaoyun
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #日期格式化
    # ALWAYS 默认
    # NON_DEFAULT 属性为默认值
    # NON_EMPTY 属性为 空（""） 或者为 NULL，
    # NON_NULL 属性为NULL 不序列化,就是为null的字段不参加序列化
    default-property-inclusion: NON_EMPTY
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      globally_quoted_identifiers: true
      use_query_cache: false
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      # 用来检测连接是否有效的sql
      validation-query: SELECT 1
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测
      # 如果空闲时间大于 timeBetweenEvictionRunsMillis，执行 validationQuery 检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
      # 归还连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 配置间隔多久才进行一次检测，检测间隔需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 3000
      # 连接保持空闲而不被清除的最小时间
      min-evictable-idle-time-millis: 300000
      # 初始化时建立连接数
      initial-size: 5
      # 最大连接池数量
      max-active: 10
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 3000
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      druid.connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

custom:
  encoding: UTF-8
  datasource:
    url-param: serverTimezone=UTC&useUnicode=true&characterEncoding=${custom.encoding}&useSSL=false&serverTimezone=Asia/Shanghai