spring:
  devtools:
    restart:
      enabled: true #热部署是否生效
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/zhaoyun?${custom.datasource.url-param}
    username: root
    password: tianlian@123
    druid:
      db-type: mysql
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true

springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: ${springfox.documentation.enabled}