spring:
  devtools:
    restart:
      enabled: true #热部署是否生效
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/zhaoyun?${custom.datasource.url-param}
    username: root
    password: tianlian@123

springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: ${springfox.documentation.enabled}
