server:
  port: 8080
  servlet:
    context-path:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: zhaoyun
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #日期格式化
    # ALWAYS 默认
    # NON_DEFAULT 属性为默认值
    # NON_EMPTY 属性为 空（""） 或者为 NULL，
    # NON_NULL 属性为NULL 不序列化,就是为null的字段不参加序列化
    default-property-inclusion: NON_EMPTY
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  cache:
    type: redis #默认缓存
  redis:
    timeout: 300 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

custom:
  swagger:
    oauth:
      auth-server-url: http://localhost:8080
      client:
        client-id: swagger
        client-secret: swagger